scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: teste
  honor_timestamps: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.0.110:3000